import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { Linking, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { palette, styles as dashboardStyles } from '@/styles/index.styles';

type Params = { demoEmail?: string; income?: string; expenses?: string; currency?: string; profilePicture?: string };
const faqs = ['How to use FinWise?', 'How much does it cost to use FinWise?', 'How to contact support?', 'How can I reset my password if I forget it?', 'Are there any privacy or data security measures in place?', 'Can I customize settings within the application?', 'How can I delete my account?', 'How do I access my expense history?', 'Can I use the app offline?'];
const categories = ['General', 'Account', 'Services'];

export default function HelpScreen() {
  const params = useLocalSearchParams<Params>();
  const [tab, setTab] = useState<'faq' | 'contact'>('faq');
  const [category, setCategory] = useState('General');
  const [query, setQuery] = useState('');
  const [expanded, setExpanded] = useState<number | null>(null);
  const goProfile = () => router.replace({ pathname: '/profile', params });
  const visibleFaqs = faqs.filter((faq) => faq.toLowerCase().includes(query.toLowerCase()));
  return <SafeAreaView style={styles.safeArea}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={goProfile} style={styles.headerIcon} accessibilityLabel="Go back to profile"><Ionicons name="arrow-back" size={20} color="#FFFFFF" /></Pressable><Text style={styles.headerTitle}>Help &amp; FAQs</Text><Pressable style={dashboardStyles.notificationButton} accessibilityLabel="Open notifications"><Ionicons name="notifications-outline" size={19} color={palette.ink} /></Pressable></View><View style={styles.panel}><Text style={styles.prompt}>How Can We Help You?</Text><View style={styles.tabs}><Pressable onPress={() => setTab('faq')} style={[styles.tab, tab === 'faq' && styles.activeTab]}><Text style={styles.tabText}>FAQ</Text></Pressable><Pressable onPress={() => setTab('contact')} style={[styles.tab, tab === 'contact' && styles.activeTab]}><Text style={styles.tabText}>Contact Us</Text></Pressable></View>{tab === 'faq' ? <><View style={styles.categories}>{categories.map((item) => <Pressable key={item} onPress={() => setCategory(item)} style={[styles.category, category === item && styles.categoryActive]}><Text style={styles.categoryText}>{item}</Text></Pressable>)}</View><TextInput value={query} onChangeText={setQuery} placeholder="Search" placeholderTextColor={palette.muted} style={styles.search} />{visibleFaqs.map((faq) => { const index = faqs.indexOf(faq); return <Pressable key={faq} onPress={() => setExpanded(expanded === index ? null : index)} style={styles.faqRow}><View style={styles.faqCopy}><Text style={styles.faqText}>{faq}</Text>{expanded === index && <Text style={styles.answer}>Find this feature in your FINORA account settings or dashboard.</Text>}</View><Ionicons name={expanded === index ? 'chevron-up' : 'chevron-down'} size={16} color={palette.ink} /></Pressable>; })}</> : <View style={styles.contactList}><ContactRow icon="headset-outline" title="Customer Service" onPress={() => Linking.openURL('mailto:support@finora.app')} /><ContactRow icon="globe-outline" title="Website" onPress={() => Linking.openURL('https://finora.app')} /><ContactRow icon="logo-facebook" title="Facebook" onPress={() => Linking.openURL('https://facebook.com')} /><ContactRow icon="logo-whatsapp" title="Whatsapp" onPress={() => Linking.openURL('https://wa.me/')} /><ContactRow icon="logo-instagram" title="Instagram" onPress={() => Linking.openURL('https://instagram.com')} /></View>}</View></ScrollView><View style={dashboardStyles.bottomNav}>{['home-outline', 'search-outline', 'swap-horizontal-outline', 'layers-outline', 'person-outline'].map((icon, index) => <Pressable key={icon} onPress={index === 0 ? () => router.replace({ pathname: '/', params }) : index === 4 ? goProfile : undefined} style={[dashboardStyles.navItem, index === 4 && dashboardStyles.navItemActive]}><Ionicons name={icon as keyof typeof Ionicons.glyphMap} size={23} color={palette.ink} /></Pressable>)}</View></SafeAreaView>;
}
function ContactRow({ icon, title, onPress }: { icon: keyof typeof Ionicons.glyphMap; title: string; onPress: () => void }) { return <Pressable onPress={onPress} style={styles.contactRow}><View style={styles.contactIcon}><Ionicons name={icon} size={17} color="#FFFFFF" /></View><Text style={styles.contactTitle}>{title}</Text><Ionicons name="chevron-forward" size={16} color={palette.ink} /></Pressable>; }
const styles = StyleSheet.create({ safeArea: { flex: 1, backgroundColor: '#ECF8ED' }, content: { flexGrow: 1, paddingBottom: 30 }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 18, paddingTop: 9, paddingBottom: 21, backgroundColor: palette.teal }, headerIcon: { width: 38, height: 38, justifyContent: 'center' }, headerTitle: { color: palette.ink, fontSize: 14, fontWeight: '700' }, panel: { flex: 1, padding: 20, borderTopLeftRadius: 38, borderTopRightRadius: 38, backgroundColor: '#F8FCF8' }, prompt: { color: palette.ink, fontSize: 12, fontWeight: '800', textAlign: 'center', marginBottom: 12 }, tabs: { flexDirection: 'row', gap: 8, padding: 4, borderRadius: 12, backgroundColor: '#D8F2DC' }, tab: { flex: 1, alignItems: 'center', paddingVertical: 9, borderRadius: 9 }, activeTab: { backgroundColor: palette.teal }, tabText: { color: palette.ink, fontSize: 10, fontWeight: '700' }, categories: { flexDirection: 'row', justifyContent: 'space-around', marginTop: 9, paddingVertical: 6, borderRadius: 7, backgroundColor: '#D8F2DC' }, category: { flex: 1, alignItems: 'center' }, categoryActive: { borderRadius: 6, backgroundColor: '#C6E9CF' }, categoryText: { color: palette.ink, fontSize: 8, paddingVertical: 4 }, search: { height: 31, marginVertical: 8, paddingHorizontal: 9, borderWidth: 1, borderColor: palette.teal, borderRadius: 5, color: palette.ink, fontSize: 9 }, faqRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#E0EEE3' }, faqCopy: { flex: 1, paddingRight: 10 }, faqText: { color: palette.muted, fontSize: 9 }, answer: { color: palette.ink, fontSize: 9, lineHeight: 14, marginTop: 5 }, contactList: { marginTop: 20 }, contactRow: { flexDirection: 'row', alignItems: 'center', minHeight: 48, borderBottomWidth: 1, borderBottomColor: '#E0EEE3' }, contactIcon: { width: 27, height: 27, alignItems: 'center', justifyContent: 'center', marginRight: 10, borderRadius: 14, backgroundColor: palette.teal }, contactTitle: { flex: 1, color: palette.ink, fontSize: 10, fontWeight: '700' } });
